# Message shown when a player is kicked for using a VPN/proxy
kick-message: "§cConnections via VPN or proxy are not allowed!"

# Debug mode for detailed logs
debug-mode: false

# Whitelist: Players that will never be blocked
whitelist:
  - "Basti20999"