name: AntiVPN
version: '1.0'
main: com.basti20999.antiVpn.AntiVPN
api-version: '1.21'
authors: [ Basti20999 ]
commands:
  antivpn:
    description: AntiVPN Befehle
    usage: /antivpn <reload|whitelist>
    permission: antivpn.admin
permissions:
  antivpn.admin:
    description: Zugriff auf alle AntiVPN Befehle
    default: op
